title: Geronimo Poppino
email: developer@geronimo.guru
name: Geronimo Poppino
theme: jekyll-theme-tactile
github_username: gpoppino
linkedin_username: geronimo-poppino
description: Personal Web Site of Geronimo Poppino
gems:
    - jekyll-octicons
