title: Geronimo Poppino
email: gresco@gmail.com
author: Geronimo Poppino

theme: jekyll-theme-tactile

github_username: gpoppino
linkedin_username: geronimo-poppino
flickr_username: _geronimo_
instagram_username: geropop
description: My Personal Web Site

minima:
date_format: "%b %-d, %Y"

kramdown:
    input: GFM

gems:
    - jemoji
    - jekyll-paginate
    - github-pages
